# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import main_qrc_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(906, 686)
        MainWindow.setMinimumSize(QSize(906, 686))
        MainWindow.setMaximumSize(QSize(906, 686))
        MainWindow.setDockNestingEnabled(False)
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.action_2 = QAction(MainWindow)
        self.action_2.setObjectName(u"action_2")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.action_3 = QAction(MainWindow)
        self.action_3.setObjectName(u"action_3")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(180, 40, 751, 601))
        font = QFont()
        font.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QCursor(Qt.ArrowCursor))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setIconSize(QSize(24, 24))
        self.tabWidget.setElideMode(Qt.ElideMiddle)
        self.tabWidgetPage1 = QWidget()
        self.tabWidgetPage1.setObjectName(u"tabWidgetPage1")
        self.btn_img_stitching = QPushButton(self.tabWidgetPage1)
        self.btn_img_stitching.setObjectName(u"btn_img_stitching")
        self.btn_img_stitching.setGeometry(QRect(50, 240, 101, 101))
        font1 = QFont()
        font1.setFamily(u"SimSun")
        font1.setPointSize(9)
        font1.setBold(False)
        font1.setWeight(50)
        font1.setStrikeOut(False)
        self.btn_img_stitching.setFont(font1)
        self.btn_img_stitching.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_img_stitching.setAcceptDrops(False)
        self.btn_img_stitching.setStyleSheet(u"QPushButton:hover{\n"
"	border-style:solid;\n"
"	border-width: 3px;\n"
"	border-color: #999999;\n"
"	border-radius: 10px;\n"
"	background-color: rgb(179, 216, 255);\n"
"	border-color: rgb(102, 161, 255);\n"
"}\n"
"QPushButton{\n"
"	border-style:solid;\n"
"	border-width: 1px;\n"
"	border-color: rgb(80, 80, 80);\n"
"	border-radius: 10px;\n"
"	background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon = QIcon()
        icon.addFile(u":/icons/icon/puzzle.png", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u":/icons/icon/puzzle2.png", QSize(), QIcon.Active, QIcon.On)
        self.btn_img_stitching.setIcon(icon)
        self.btn_img_stitching.setIconSize(QSize(64, 64))
        self.btn_img_stitching.setCheckable(False)
        self.btn_img_stitching.setAutoRepeat(False)
        self.btn_img_stitching.setAutoExclusive(False)
        self.btn_img_stitching.setAutoDefault(False)
        self.btn_img_stitching.setFlat(False)
        self.btn_tongue = QPushButton(self.tabWidgetPage1)
        self.btn_tongue.setObjectName(u"btn_tongue")
        self.btn_tongue.setGeometry(QRect(170, 240, 101, 101))
        font2 = QFont()
        font2.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font2.setPointSize(11)
        font2.setBold(False)
        font2.setWeight(50)
        font2.setStrikeOut(False)
        self.btn_tongue.setFont(font2)
        self.btn_tongue.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_tongue.setAcceptDrops(False)
        self.btn_tongue.setStyleSheet(u"QPushButton:hover{\n"
"	border-style:solid;\n"
"	border-width: 3px;\n"
"	border-color: #999999;\n"
"	border-radius: 10px;\n"
"	background-color: rgb(179, 216, 255);\n"
"	border-color: rgb(102, 161, 255);\n"
"}\n"
"QPushButton{\n"
"	border-style:solid;\n"
"	border-width: 1px;\n"
"	border-color: rgb(80, 80, 80);\n"
"	border-radius: 10px;\n"
"	background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon1 = QIcon()
        icon1.addFile(u":/icons/icon/tongue.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_tongue.setIcon(icon1)
        self.btn_tongue.setIconSize(QSize(64, 64))
        self.btn_tongue.setCheckable(False)
        self.btn_tongue.setAutoRepeat(False)
        self.btn_tongue.setAutoExclusive(False)
        self.btn_tongue.setAutoDefault(False)
        self.btn_tongue.setFlat(False)
        self.btn_ml = QPushButton(self.tabWidgetPage1)
        self.btn_ml.setObjectName(u"btn_ml")
        self.btn_ml.setGeometry(QRect(290, 240, 101, 101))
        self.btn_ml.setFont(font2)
        self.btn_ml.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ml.setAcceptDrops(False)
        self.btn_ml.setStyleSheet(u"QPushButton:hover{\n"
"	border-style:solid;\n"
"	border-width: 3px;\n"
"	border-color: #999999;\n"
"	border-radius: 10px;\n"
"	background-color: rgb(179, 216, 255);\n"
"	border-color: rgb(102, 161, 255);\n"
"}\n"
"QPushButton{\n"
"	border-style:solid;\n"
"	border-width: 1px;\n"
"	border-color: rgb(80, 80, 80);\n"
"	border-radius: 10px;\n"
"	background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon2 = QIcon()
        icon2.addFile(u":/icons/icon/pngwing.com.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ml.setIcon(icon2)
        self.btn_ml.setIconSize(QSize(64, 64))
        self.btn_ml.setCheckable(False)
        self.btn_ml.setAutoRepeat(False)
        self.btn_ml.setAutoExclusive(False)
        self.btn_ml.setAutoDefault(False)
        self.btn_ml.setFlat(False)
        self.label_10 = QLabel(self.tabWidgetPage1)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(70, 340, 71, 31))
        font3 = QFont()
        font3.setPointSize(12)
        self.label_10.setFont(font3)
        self.label_11 = QLabel(self.tabWidgetPage1)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(190, 340, 71, 31))
        self.label_11.setFont(font3)
        self.label_12 = QLabel(self.tabWidgetPage1)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(300, 340, 91, 31))
        self.label_12.setFont(font3)
        self.label_12.setIndent(1)
        self.new_2 = QPushButton(self.tabWidgetPage1)
        self.new_2.setObjectName(u"new_2")
        self.new_2.setGeometry(QRect(50, 60, 101, 101))
        self.new_2.setFont(font1)
        self.new_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.new_2.setAcceptDrops(False)
        self.new_2.setStyleSheet(u"QPushButton:hover{\n"
"	border-style:solid;\n"
"	border-width: 3px;\n"
"	border-color: #999999;\n"
"	border-radius: 10px;\n"
"	background-color: rgb(179, 216, 255);\n"
"	border-color: rgb(102, 161, 255);\n"
"}\n"
"QPushButton{\n"
"	border-style:solid;\n"
"	border-width: 1px;\n"
"	border-color: rgb(80, 80, 80);\n"
"	border-radius: 10px;\n"
"	background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon3 = QIcon()
        icon3.addFile(u":/icons/icon/add-file-icon-18.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.new_2.setIcon(icon3)
        self.new_2.setIconSize(QSize(64, 64))
        self.new_2.setCheckable(False)
        self.new_2.setAutoRepeat(False)
        self.new_2.setAutoExclusive(False)
        self.new_2.setAutoDefault(False)
        self.new_2.setFlat(False)
        self.label_13 = QLabel(self.tabWidgetPage1)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(80, 160, 41, 31))
        self.label_13.setFont(font3)
        self.new_3 = QPushButton(self.tabWidgetPage1)
        self.new_3.setObjectName(u"new_3")
        self.new_3.setGeometry(QRect(170, 60, 101, 101))
        self.new_3.setFont(font1)
        self.new_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.new_3.setAcceptDrops(False)
        self.new_3.setStyleSheet(u"QPushButton:hover{\n"
"	border-style:solid;\n"
"	border-width: 3px;\n"
"	border-color: #999999;\n"
"	border-radius: 10px;\n"
"	background-color: rgb(179, 216, 255);\n"
"	border-color: rgb(102, 161, 255);\n"
"}\n"
"QPushButton{\n"
"	border-style:solid;\n"
"	border-width: 1px;\n"
"	border-color: rgb(80, 80, 80);\n"
"	border-radius: 10px;\n"
"	background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon4 = QIcon()
        icon4.addFile(u":/icons/icon/open-archive-svgrepo-com.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.new_3.setIcon(icon4)
        self.new_3.setIconSize(QSize(64, 64))
        self.new_3.setCheckable(False)
        self.new_3.setAutoRepeat(False)
        self.new_3.setAutoExclusive(False)
        self.new_3.setAutoDefault(False)
        self.new_3.setFlat(False)
        self.label_30 = QLabel(self.tabWidgetPage1)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(200, 160, 41, 31))
        self.label_30.setFont(font3)
        icon5 = QIcon()
        icon5.addFile(u":/icons/icon/home.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.tabWidgetPage1, icon5, "")
        self.tabWidgetPage2 = QWidget()
        self.tabWidgetPage2.setObjectName(u"tabWidgetPage2")
        self.label = QLabel(self.tabWidgetPage2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 71, 31))
        font4 = QFont()
        font4.setFamily(u"Microsoft YaHei UI")
        font4.setPointSize(12)
        font4.setBold(False)
        font4.setWeight(50)
        self.label.setFont(font4)
        self.img_path = QTextEdit(self.tabWidgetPage2)
        self.img_path.setObjectName(u"img_path")
        self.img_path.setGeometry(QRect(110, 20, 501, 31))
        font5 = QFont()
        font5.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font5.setPointSize(10)
        font5.setBold(False)
        font5.setWeight(50)
        self.img_path.setFont(font5)
        self.img_path.setToolTipDuration(1)
        self.img_path.setReadOnly(True)
        self.btn_choose_img_path = QPushButton(self.tabWidgetPage2)
        self.btn_choose_img_path.setObjectName(u"btn_choose_img_path")
        self.btn_choose_img_path.setEnabled(True)
        self.btn_choose_img_path.setGeometry(QRect(620, 20, 81, 31))
        font6 = QFont()
        font6.setFamily(u"Microsoft YaHei UI")
        font6.setPointSize(10)
        font6.setBold(False)
        font6.setWeight(50)
        self.btn_choose_img_path.setFont(font6)
        self.btn_choose_img_path.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_choose_img_path.setMouseTracking(False)
        self.btn_choose_img_path.setAutoFillBackground(False)
        self.btn_choose_img_path.setStyleSheet(u"QPushButton{\n"
"	background-color: rgb(241, 241, 241);\n"
"	border-style:solid;\n"
"	border-width: 1px;\n"
"	border-color: rgb(103, 103, 103);\n"
"	border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"	background-color: rgb(179, 216, 255);\n"
"	border-color: rgb(102, 161, 255);\n"
"}")
        self.btn_stitch = QPushButton(self.tabWidgetPage2)
        self.btn_stitch.setObjectName(u"btn_stitch")
        self.btn_stitch.setEnabled(True)
        self.btn_stitch.setGeometry(QRect(620, 500, 81, 31))
        self.btn_stitch.setFont(font6)
        self.btn_stitch.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_stitch.setMouseTracking(False)
        self.btn_stitch.setLayoutDirection(Qt.RightToLeft)
        self.btn_stitch.setAutoFillBackground(False)
        self.btn_stitch.setStyleSheet(u"QPushButton{\n"
"	background-color: rgb(241, 241, 241);\n"
"	border-style:solid;\n"
"	border-width: 1px;\n"
"	border-color: rgb(103, 103, 103);\n"
"	border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"	background-color: rgb(179, 216, 255);\n"
"	border-color: rgb(102, 161, 255);\n"
"}\n"
"")
        self.btn_stitch.setCheckable(False)
        self.btn_stitch.setAutoDefault(False)
        self.btn_stitch.setFlat(False)
        self.progressBar = QProgressBar(self.tabWidgetPage2)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QRect(20, 540, 681, 12))
        font7 = QFont()
        font7.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font7.setPointSize(8)
        font7.setBold(False)
        font7.setWeight(50)
        self.progressBar.setFont(font7)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet(u"QProgressBar {\n"
"     border-radius: 6px;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"	background-color: rgb(89, 183, 255);\n"
"     width: 20px;\n"
" }")
        self.progressBar.setValue(50)
        self.progressBar.setAlignment(Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.listWidget = QListWidget(self.tabWidgetPage2)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(20, 100, 681, 391))
        self.listWidget.setFont(font5)
        self.listWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.listWidget.setDragDropMode(QAbstractItemView.DragDrop)
        self.listWidget.setDefaultDropAction(Qt.IgnoreAction)
        self.listWidget.setSelectionMode(QAbstractItemView.MultiSelection)
        self.listWidget.setIconSize(QSize(150, 150))
        self.listWidget.setMovement(QListView.Free)
        self.listWidget.setFlow(QListView.LeftToRight)
        self.listWidget.setProperty("isWrapping", True)
        self.listWidget.setResizeMode(QListView.Adjust)
        self.listWidget.setSpacing(0)
        self.listWidget.setViewMode(QListView.IconMode)
        self.listWidget.setUniformItemSizes(True)
        self.frame_2 = QFrame(self.tabWidgetPage2)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(20, 500, 221, 31))
        font8 = QFont()
        font8.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font8.setPointSize(11)
        font8.setBold(False)
        font8.setWeight(50)
        font8.setKerning(True)
        self.frame_2.setFont(font8)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_16 = QLabel(self.frame_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(70, 0, 16, 21))
        font9 = QFont()
        font9.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font9.setPointSize(10)
        font9.setBold(False)
        font9.setWeight(50)
        font9.setKerning(True)
        self.label_16.setFont(font9)
        self.label_16.setLineWidth(1)
        self.label_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_16.setIndent(-1)
        self.img_all_num = QLabel(self.frame_2)
        self.img_all_num.setObjectName(u"img_all_num")
        self.img_all_num.setGeometry(QRect(90, 0, 31, 21))
        self.img_all_num.setFont(font9)
        self.img_all_num.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.img_all_num.setIndent(-1)
        self.label_18 = QLabel(self.frame_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(110, 0, 16, 21))
        self.label_18.setFont(font9)
        self.label_18.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_19 = QLabel(self.frame_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(150, 0, 31, 21))
        self.label_19.setFont(font9)
        self.label_19.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.img_selected_num = QLabel(self.frame_2)
        self.img_selected_num.setObjectName(u"img_selected_num")
        self.img_selected_num.setGeometry(QRect(180, 0, 21, 21))
        self.img_selected_num.setFont(font9)
        self.img_selected_num.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_21 = QLabel(self.frame_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(200, 0, 16, 21))
        self.label_21.setFont(font9)
        self.label_21.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.check_box_select_all = QCheckBox(self.frame_2)
        self.check_box_select_all.setObjectName(u"check_box_select_all")
        self.check_box_select_all.setGeometry(QRect(0, 0, 51, 16))
        self.check_box_select_all.setFont(font9)
        self.check_box_select_all.setIconSize(QSize(16, 16))
        self.label_17 = QLabel(self.tabWidgetPage2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 60, 71, 31))
        self.label_17.setFont(font4)
        self.stitch_mode = QComboBox(self.tabWidgetPage2)
        self.stitch_mode.addItem("")
        self.stitch_mode.addItem("")
        self.stitch_mode.setObjectName(u"stitch_mode")
        self.stitch_mode.setGeometry(QRect(110, 61, 71, 31))
        self.stitch_mode.setFont(font5)
        self.stitch_mode.setStyleSheet(u"")
        icon6 = QIcon()
        icon6.addFile(u":/icons/icon/camera.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.tabWidgetPage2, icon6, "")
        self.tabWidgetPage3 = QWidget()
        self.tabWidgetPage3.setObjectName(u"tabWidgetPage3")
        self.label_20 = QLabel(self.tabWidgetPage3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(160, 140, 361, 121))
        palette = QPalette()
        brush = QBrush(QColor(209, 209, 209, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(120, 120, 120, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_20.setPalette(palette)
        font10 = QFont()
        font10.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font10.setPointSize(50)
        font10.setBold(True)
        font10.setWeight(75)
        font10.setKerning(True)
        self.label_20.setFont(font10)
        self.label_20.setMargin(0)
        self.label_20.setIndent(-1)
        icon7 = QIcon()
        icon7.addFile(u":/icons/icon/yin-yang.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.tabWidgetPage3, icon7, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_22 = QLabel(self.tab)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(160, 140, 361, 121))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.label_22.setPalette(palette1)
        self.label_22.setFont(font10)
        self.label_22.setMargin(0)
        self.label_22.setIndent(-1)
        icon8 = QIcon()
        icon8.addFile(u":/icons/icon/system-monitor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.tab, icon8, "")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 40, 141, 181))
        self.label_2.setPixmap(QPixmap(u":/pictures/resource/Sigmund_Freud,_by_Max_Halberstadt_(cropped).jpg"))
        self.label_2.setScaledContents(True)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(20, 280, 141, 341))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 0, 41, 21))
        font11 = QFont()
        font11.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font11.setPointSize(11)
        self.label_4.setFont(font11)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 30, 41, 21))
        self.label_5.setFont(font11)
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 0, 101, 21))
        self.label_6.setFont(font11)
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 30, 101, 21))
        self.label_7.setFont(font11)
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 60, 41, 21))
        self.label_8.setFont(font11)
        self.label_14 = QLabel(self.frame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 90, 81, 21))
        self.label_14.setFont(font11)
        self.label_15 = QLabel(self.frame)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(40, 60, 101, 21))
        self.label_15.setFont(font11)
        self.toolBox = QToolBox(self.frame)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setGeometry(QRect(0, 120, 141, 221))
        font12 = QFont()
        font12.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font12.setPointSize(10)
        self.toolBox.setFont(font12)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 141, 155))
        self.toolBox.addItem(self.page_2, u"\u75c5\u53f2")
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setGeometry(QRect(0, 0, 141, 155))
        self.toolBox.addItem(self.page_3, u"\u5176\u5b83")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 240, 71, 21))
        font13 = QFont()
        font13.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font13.setPointSize(12)
        font13.setBold(True)
        font13.setWeight(75)
        self.label_3.setFont(font13)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 906, 23))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        self.menu_4 = QMenu(self.menubar)
        self.menu_4.setObjectName(u"menu_4")
        self.menu_5 = QMenu(self.menubar)
        self.menu_5.setObjectName(u"menu_5")
        self.menu_6 = QMenu(self.menubar)
        self.menu_6.setObjectName(u"menu_6")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(True)
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu_2.addAction(self.actionCopy)
        self.menu_2.addAction(self.actionPaste)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.btn_img_stitching.setDefault(False)
        self.btn_tongue.setDefault(False)
        self.btn_ml.setDefault(False)
        self.new_2.setDefault(False)
        self.new_3.setDefault(False)
        self.btn_stitch.setDefault(False)
        self.toolBox.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa", None))
#if QT_CONFIG(shortcut)
        self.action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_2.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
#if QT_CONFIG(shortcut)
        self.action_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.action_3.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
#if QT_CONFIG(shortcut)
        self.action_3.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(statustip)
        self.btn_img_stitching.setStatusTip(QCoreApplication.translate("MainWindow", u"\u53e3\u8154\u626b\u63cf\u56fe\u50cf\u62fc\u63a5", None))
#endif // QT_CONFIG(statustip)
        self.btn_img_stitching.setText("")
#if QT_CONFIG(statustip)
        self.btn_tongue.setStatusTip(QCoreApplication.translate("MainWindow", u"\u820c\u50cf\u5206\u6790", None))
#endif // QT_CONFIG(statustip)
        self.btn_tongue.setText("")
#if QT_CONFIG(statustip)
        self.btn_ml.setStatusTip(QCoreApplication.translate("MainWindow", u"\u9f3b\u54bd\u764c\u8bca\u65ad", None))
#endif // QT_CONFIG(statustip)
        self.btn_ml.setText("")
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u62fc\u63a5", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u820c\u50cf\u5206\u6790", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u9f3b\u54bd\u764c\u8bca\u65ad", None))
#if QT_CONFIG(tooltip)
        self.new_2.setToolTip(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u60a3\u8005\u4fe1\u606f", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.new_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u60a3\u8005\u4fe1\u606f", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.new_2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.new_2.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa", None))
#if QT_CONFIG(tooltip)
        self.new_3.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u60a3\u8005\u4fe1\u606f", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.new_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u60a3\u8005\u4fe1\u606f", None))
#endif // QT_CONFIG(statustip)
        self.new_3.setText("")
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), "")
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u76ee\u5f55\uff1a", None))
#if QT_CONFIG(tooltip)
        self.img_path.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.img_path.setStatusTip(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u62fc\u63a5\u56fe\u7247\u6240\u5728\u6587\u4ef6\u5939", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.img_path.setWhatsThis(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u62fc\u63a5\u56fe\u7247\u6240\u5728\u6587\u4ef6\u5939", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.btn_choose_img_path.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u9009\u62e9\u62fc\u63a5\u56fe\u7247\u6240\u5728\u6587\u4ef6\u5939</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_choose_img_path.setStatusTip(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u62fc\u63a5\u56fe\u7247\u6240\u5728\u6587\u4ef6\u5939", None))
#endif // QT_CONFIG(statustip)
        self.btn_choose_img_path.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9", None))
#if QT_CONFIG(tooltip)
        self.btn_stitch.setToolTip(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u62fc\u63a5\u6240\u9009\u56fe\u7247", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_stitch.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u62fc\u63a5\u6240\u9009\u56fe\u7247", None))
#endif // QT_CONFIG(statustip)
        self.btn_stitch.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u62fc\u63a5", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u5171", None))
        self.img_all_num.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u5f20", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u5df2\u9009", None))
        self.img_selected_num.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u5f20", None))
#if QT_CONFIG(statustip)
        self.check_box_select_all.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5168\u9009\u6216\u53d6\u6d88\u5168\u9009", None))
#endif // QT_CONFIG(statustip)
        self.check_box_select_all.setText(QCoreApplication.translate("MainWindow", u"\u5168\u9009", None))
#if QT_CONFIG(shortcut)
        self.check_box_select_all.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u5f0f\u9009\u62e9\uff1a", None))
        self.stitch_mode.setItemText(0, QCoreApplication.translate("MainWindow", u"\u626b\u63cf", None))
        self.stitch_mode.setItemText(1, QCoreApplication.translate("MainWindow", u"\u5168\u666f", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u62fc\u63a5", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u656c \u8bf7 \u671f \u5f85", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), QCoreApplication.translate("MainWindow", u"\u820c\u50cf\u5206\u6790", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"\u656c \u8bf7 \u671f \u5f85", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u9f3b\u54bd\u764c\u8bca\u65ad", None))
        self.label_2.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u59d3\u540d\uff1a", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u5e74\u9f84\uff1a", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u4e54\u6cbb\u00b7\u5f17\u6d1b\u4f0a\u5fb7", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"165", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u6027\u522b\uff1a", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u57fa\u672c\u4fe1\u606f\uff1a", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u7537", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QCoreApplication.translate("MainWindow", u"\u75c5\u53f2", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QCoreApplication.translate("MainWindow", u"\u5176\u5b83", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u60a3\u8005\u4fe1\u606f", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u5de5\u5177", None))
        self.menu_4.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.menu_5.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe", None))
        self.menu_6.setTitle(QCoreApplication.translate("MainWindow", u"\u9009\u62e9", None))
    # retranslateUi

